export const globalDataType = {
  SET_GLOBALDATA_INFO: "SET_GLOBALDATA_INFO",
  CLEAR_GLOBALDATA_INFO: "CLEAR_GLOBALDATA_INFO"
};

export const adminType = {
  SET_ADMIN_INFO: "SET_ADMIN_INFO",
  CLEAR_ADMIN_INFO: "CLEAR_ADMIN_INFO"
};

export const formDataType = {
  SET_FORMDATA_INFO: "SET_FORMDATA_INFO",
  CLEAR_FORMDATA_INFO: "CLEAR_FORMDATA_INFO"
};

export const formFilterType = {
  SET_FORMFILTER_INFO: "SET_FORMFILTER_INFO",
  CLEAR_FORMFILTER_INFO: "CLEAR_FORMFILTER_INFO"
};

export const editorType = {
  SET_EDITOR_INFO: "SET_EDITOR_INFO",
  CLEAR_EDITOR_INFO: "CLEAR_EDITOR_INFO"
};
