export const type = {
    REQUEST_DATA: 'REQUEST_DATA',
    RECEIVE_DATA: 'RECEIVE_DATA'
}

export const adminType = {
    SET_ADMIN_INFO: 'SET_ADMIN_INFO',
    CLEAR_ADMIN_INFO: 'CLEAR_ADMIN_INFO'
}

export const panesType = {
    SET_PANES_INFO:"SET_PANES_INFO",
    CLEAR_PANES_INFO:"CLEAR_PANES_INFO",
    INIT_PANES_INFO:"INIT_PANES_INFO"
}

export const urlsKeyType = {
    SET_URLSKEY_INFO:"SET_URLSKEY_INFO",
    CLEAR_URLSKEY_INFO:"CLEAR_URLSKEY_INFO",
    INIT_URLSKEY_INFO:"INIT_URLSKEY_INFO"
}

export const formDataType = {
    SET_FORMDATA_INFO:"SET_FORMDATA_INFO",
    CLEAR_FORMDATA_INFO:"CLEAR_FORMDATA_INFO"
}

export const formFilterType = {
    SET_FORMFILTER_INFO:"SET_FORMFILTER_INFO",
    CLEAR_FORMFILTER_INFO:"CLEAR_FORMFILTER_INFO"
}